server:
  port: 8089

spring:
  # mysql
  datasource:
    firstdoc:
      username: bhz
      password: Bhz123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/firstDoc?serverTimezone=UTC
    klin:
      username: bhz
      password: Bhz123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/klin?serverTimezone=UTC

  # redis
  redis:
    host: localhost
    port: 6379
    database: 0
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # ????
  mapper-locations: classpath:mapping/firstDoc/*.xml,classpath:mapping/klin/*.xml

